# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VilaviFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=5)),
                ('sid', models.IntegerField(blank=True, max_length=5)),
                ('gpv', models.IntegerField()),
                ('r', models.IntegerField()),
                ('q', models.CharField(max_length=10)),
                ('g', models.IntegerField(max_length=1)),
                ('ul', models.IntegerField()),
                ('un', models.CharField(max_length=256)),
                ('up', models.CharField(max_length=12)),
                ('ua', models.CharField(max_length=50)),
                ('uas', models.CharField(max_length=30)),
                ('uav', models.CharField(max_length=50)),
                ('dd', models.BooleanField()),
            ],
        ),
    ]
