# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_vilavifetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilavifetch',
            name='g',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vilavifetch',
            name='sid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vilavifetch',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
