# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170922_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Vasya', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Vasya', max_length=50),
        ),
    ]
