# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170922_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
