# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_vilavifetch_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vilavifetch',
            old_name='is_active',
            new_name='active',
        ),
    ]
