# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170927_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='profile',
            name='classmate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.City'),
        ),
    ]
