# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170929_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 12, 46, 42, 521089, tzinfo=utc)),
        ),
    ]
