# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20171008_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 16, 6, 27, 179410, tzinfo=utc)),
        ),
    ]
