# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20171008_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='vilavifetch',
            name='lastTimeShow',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 15, 19, 50, 333778, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vilavifetch',
            name='numberOfShow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 15, 19, 50, 332796, tzinfo=utc)),
        ),
    ]
